# Generated by Django 3.2.12 on 2022-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
            ],
        ),
    ]
