# Generated by Django 3.2.12 on 2022-03-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
