# Generated by Django 3.2.12 on 2022-03-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20220318_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
