# Generated by Django 3.2.12 on 2022-03-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_blockedwords'),
        ('category', '0012_post_tags'),
    ]

    operations = [
    ]
