# Generated by Django 3.2.12 on 2022-03-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_merge_0004_blockedwords_0012_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
