# Generated by Django 3.2.12 on 2022-03-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_alter_category_catsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catsub',
            field=models.BooleanField(default=True),
        ),
    ]
