# Generated by Django 3.2.12 on 2022-03-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_alter_category_catsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catsub',
        ),
    ]
